env:
    global:
        - CC_TEST_REPORTER_ID=6870c204ea2da7c81fdf40369b4f752340d22e7c51a73d429f48381ad3f1bd34

language: go
go:
    - 1.7

install:
    - 

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter

script:
    - go test -coverprofile=c.out

after_success:
    - ./cc-test-reporter -t gocov
